### ISSUE TITLE
Misty step does not suspend animation

### ISSUE THREAD

**Issue by SR5060** [kandashi/Macros#5]
Apologies if you are still working on these, but wanted to give feedback just in case. It looks like misty step still animates the token when moving to the destination in v8.6

**Comment by SR5060** [comment]
I believe this is due to an issue with the module token attacher. feel free to close if you don't want to address compatibility with that module.

**Comment by kandashi** [comment]
If you can confirm that Token Attacher causes this, that would be great

**Comment by SR5060** [comment]
Tested it and that was indeed the issue, however the most recent Token Attacher update has resolved the issue.
